### ISSUE TITLE
Can't import LocationGetLocationServices in android studio

### ISSUE THREAD

**Issue by Nymerea** [aporter/coursera-android#27]
Hello every body,

I can't import import into androidStudio from eclipse. Have you an idea ?
- Project LocationGetLocationServices:/home/morgan/Documents/dkit/mobile devlopment/coursera-android/Examples/LocationGetLocationServices/project.properties:
  Library reference ../../../../Classes/AndroidOnline/Coursersa-Android002/eclipse/google-play-services_lib could not be found
  Path is /home/morgan/Documents/dkit/mobile devlopment/coursera-android/Examples/LocationGetLocationServices/../../../../Classes/AndroidOnline/Coursersa-Android002/eclipse/google-play-services_lib which resolves to /home/morgan/Dropbox/dkit/Classes/AndroidOnline/Coursersa-Android002/eclipse/google-play-services_lib

**Comment by enriqif** [comment]
that scan you copy of the error? try to write clearly..

**Comment by wardweistra** [comment]
This comes from a hardcoded reference to the Google Play Services library in the project.properties file of the project you are importing.  
Make sure you have downloaded Google Play Services in the SDK manager. Then change the value for 'android.library.reference.1' in the 'project.properties' of the project you're importing to <your SDK location>/extras/google/google_play_services/libproject/google-play-services_lib.

**Comment by iamquan** [comment]
@wardweistra , @Nymerea actually you need to change value 'android.library.reference.1' equal to ../google-play-services_lib

**Comment by choirbean** [comment]
Unsubscribe
