### ISSUE TITLE
Need somebody help...

### ISSUE THREAD

**Issue by ArshaWIN** [aporter/coursera-android#31]
Hello, its my first course and mb my question is silly, but where are video lectures and other materials , I cant find it, I have only github link. Help pls!

**Comment by sid-iitb** [comment]
https://class.coursera.org/androidpart1-004/lecture

**Comment by campbe13** [comment]
Sign up for the course on coursera to get all of that info

On Thu, May 7, 2015 at 12:42 PM, ArshaWIN <notifications@github.com> wrote:

> Hello, its my first course and mb my question is silly, but where are
> video lectures and other materials , I cant find it, I have only github
> link. Help pls!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aporter/coursera-android/issues/31>.
>



-- 
___..___........__.......__
...|....|__/....|...|......|...|__|
...|....|.....\...|...|__..|...|....|

"You must be the change you wish to see in the world." Mohandas K Gandhi

**Comment by ArshaWIN** [comment]
Thank you! Now its okay!


Четверг,  7 мая 2015, 9:47 -07:00 от P Campbell <notifications@github.com>:
>Sign up for the course on coursera to get all of that info
>
>On Thu, May 7, 2015 at 12:42 PM, ArshaWIN <notifications@github.com> wrote:
>
>> Hello, its my first course and mb my question is silly, but where are
>> video lectures and other materials , I cant find it, I have only github
>> link. Help pls!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aporter/coursera-android/issues/31>.
>>
>
>
>
>-- 
>___..___........__.......__
>...|....|__/....|...|......|...|__|
>...|....|.....\...|...|__..|...|....|
>
>"You must be the change you wish to see in the world." Mohandas K Gandhi
>—
>Reply to this email directly or  view it on GitHub .


-- 
С уважением, Илья Михайленко

**Comment by ArshaWIN** [comment]
Thank you! Now its okey!



Четверг,  7 мая 2015, 9:47 -07:00 от sid-iitb <notifications@github.com>:
>https://class.coursera.org/androidpart1-004/lecture
>—
>Reply to this email directly or  view it on GitHub .


-- 
С уважением, Илья Михайленко

**Comment by oBoBuiL** [comment]
n��n  uv

------------------ �������� ------------------


    
        ������: ArshaWIN  <notifications@github.com>;
    
    
        ��������: 2015-05-08 20:24:09
    
    
        ������: aporter/coursera-android  <coursera-android@noreply.github.com>; 
    
    
        ����: (��); 
    
    
        ����: Re: [coursera-android] Need somebody help... (#31)
    

 Thank you! Now its okey!    ��������������,  7 ������ 2015, 9:47 -07:00 ���� sid-iitb <notifications@github.com>: >https://class.coursera.org/androidpart1-004/lecture >�� >Reply to this email directly or  view it on GitHub .   --  �� ������������������, �������� ��������������������   ��Reply to this email directly or view it on GitHub.

**Comment by deadlydragon00** [comment]
@ArshaWIN If this is the first time you use git ,

Steps:

**Comment by epety** [comment]
If you dont know how to use git  you can read [Set up Git](https://help.github.com/articles/set-up-git/) and [Why you failed to clone repository in GitHub ](http://blog.sudoask.com/why-you-failed-to-clone-repository-in-github) for troubleshoot .
