### ISSUE TITLE
Git:  Cloning and SSL Failure

### ISSUE THREAD

**Issue by bamcdougall** [aporter/coursera-android#35]
Hi Adam,

Do you have insight as to why I am unable to clone my fork of this Repository  (git@github.com:bamcdougall/coursera-android.git), but I am able to clone your originating fork (git@github.com:bamcdougall/coursera-android.git).

I did not change any permissions of the forks within my own Repository...just clicked each Repository's respective Fork button.

The interesting thing is that I am able to git clone git@github.com:bamcdougall/coursera-android-labs.git, which is my fork of your originating Labs Repository

Thank you and best regards.

Brendan

**Comment by epety** [comment]
You have two chooses  to clone git repository 
If you clone with HTTPS can use `git clone https://github.com/username/repo.git `
If you clone with SSH, you must generate SSH keys before clone : `git clone git@github.com:username/repo.git  `

For more read here: [Why you failed to clone repository in GitHub ](http://blog.sudoask.com/why-you-failed-to-clone-repository-in-github/)

**Comment by bamcdougall** [comment]
Thanks Epety.

I do have SSH keys and validated my connection to GitHub using "ssh -T git@github.com" as described in https://help.github.com/articles/error-repository-not-found/.  

I was able to clone a separate Repository that I forked from Adam Porter.  Not sure what is different between these two Repositories that I forked from Adam.

Brendan

**Comment by epety** [comment]
I clone you fork repo, `git clone  git@github.com:bamcdougall/coursera-android.git` it run !, 
Do not have any problem.

**Comment by bamcdougall** [comment]
That is interesting data point. Thank you

**Comment by epety** [comment]
You need close your issues !
