### ISSUE TITLE
week 2 lab 

### ISSUE THREAD

**Issue by swetadas** [aporter/coursera-android#39]
i got lots of error while performing for week 2 lab, i dont know how to rectify it plaese help me.

![p1](https://cloud.githubusercontent.com/assets/13611758/9258624/320b8732-41c2-11e5-9310-52b3ea07631e.png)
![p2](https://cloud.githubusercontent.com/assets/13611758/9258625/320bb5e0-41c2-11e5-99fa-18f635891a65.png)
![p3](https://cloud.githubusercontent.com/assets/13611758/9258626/320dc434-41c2-11e5-85fa-1ef7f089f8e7.png)
![p5](https://cloud.githubusercontent.com/assets/13611758/9258628/320f3bfc-41c2-11e5-82eb-9d8fd76574b1.png)
![p6](https://cloud.githubusercontent.com/assets/13611758/9258627/320e2370-41c2-11e5-9e38-6a4254be3f1f.png)
![p7](https://cloud.githubusercontent.com/assets/13611758/9258629/32109e66-41c2-11e5-9ec6-621d8c8e0cf2.png)
![p8](https://cloud.githubusercontent.com/assets/13611758/9258630/322529ee-41c2-11e5-8dd5-9434199fb6cc.png)
there is  further i will post you soon

**Comment by swetadas** [comment]
![p1](https://cloud.githubusercontent.com/assets/13611758/9336617/25402b66-45a0-11e5-8137-8733dcf630a8.png)
![p2](https://cloud.githubusercontent.com/assets/13611758/9336619/254202a6-45a0-11e5-9a35-6597cb10e27d.png)
![p3](https://cloud.githubusercontent.com/assets/13611758/9336618/2541c71e-45a0-11e5-8346-d4754cea4092.png)
![p4](https://cloud.githubusercontent.com/assets/13611758/9336620/2542a36e-45a0-11e5-8919-74051026c9bb.png)
![p5](https://cloud.githubusercontent.com/assets/13611758/9336622/2543cb68-45a0-11e5-9ab5-e19e2b5f5981.png)
![p6](https://cloud.githubusercontent.com/assets/13611758/9336621/2542b1a6-45a0-11e5-9ad5-417752d94736.png)

**Comment by swetadas** [comment]
i am facing problem in this code thats y all my labs of week 2 was not successfull, waiting for your help sir!!!!!!

**Comment by sshiley** [comment]
Not sure why this is being sent to me, as I’m just a student. Also not sure if it’s being sent only to me, or to the whole class.

**Comment by gssrinivasan** [comment]
It's been sent to whole class unknowingly i guess, I have received it too.
I am a student as well.

**Comment by jhaas89** [comment]
Same here, I'm also a student, and unfortunately I'm also having trouble.
Sorry

**Comment by formap** [comment]
I believe it’s being sent to everyone that’s watching the repository on GitHub. You can change your preferences by going into the repository https://github.com/aporter/coursera-android/issues/39#issuecomment-132276947 <https://github.com/aporter/coursera-android/issues/39#issuecomment-132276947> and changing to Not watching (only notifies you when you’re participating or mentioned) or Ignoring (to not be notified at all).

**Comment by swetadas** [comment]
no dear i didn't personally sent you this, but posted in github section as
i am facing problems in this code. Anyways my friend i will be glad if you
help in week-2 labs as i am not able to perform it getting lots of errors
and also running behind because i am continously behind after my errors, iw
ill be glad you mail me the correct code of all week-2 labs which is
required to submit.

Thanks

**Comment by sheldonj84** [comment]
I am going to make two suggestions, first don't post your code as a screen shot of a word document. there are ways to post actual code. 

Second you should post this to the class forum you will get more help there.

**Comment by swetadas** [comment]
thanks for help

**Comment by TommyVan** [comment]
I think you should import R package into your workspace. and you should take a screenshot of the Android studio.

**Comment by swetadas** [comment]
thanks !!!!!! :)
