### ISSUE TITLE
Step 5, Lab 1: Failed to sync Gradle Build Project :TheAnswer

### ISSUE THREAD

**Issue by vik17ag** [aporter/coursera-android#41]
Hi,
After importing 'TheAnswer', I get the following message in GradleSync message box-

Error:Cause: failed to find target with hash string 'android-17' in: C:\Program Files\Android\sdk
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

Pls, help

rgds
vivek

**Comment by jakubczaplicki** [comment]
Do you have the Android-17 SDK installed ? Check in Tools > Android > SDK Manager and check to see if Android 4.2 (API 17) is installed.

**Comment by vik17ag** [comment]
Thanks a lot, i just had the latest sdk not the 17th,
So i downloaded and prob solved
