### ISSUE TITLE
Part 5, step 11: emulator: ERROR: x86: AVD cant load

### ISSUE THREAD

**Issue by vik17ag** [aporter/coursera-android#42]
When i try to start and AVD, foll message appears in Run window below -

emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure Intel HAXM is properly installed and usable.
CPU acceleration status: HAX kernel module is not installed!

Currently, i am using windows -7,
Is there any way i can run AVD on my laptop?

**Comment by filipebezerra** [comment]
You need the check if your laptop supports hardware acceleration, because HAXM is a component included in the SDK Manager, also included in the Android Studio installation.

If you detect that your laptop don't support hardware acceleration, try uninstalling HAXM:

![haxm](https://cloud.githubusercontent.com/assets/1006095/10714112/b187949e-7ac3-11e5-9e9a-fe6dd86469ab.PNG)

**Comment by alex848** [comment]
how to check whether  my laptop supports hxam or not


On Sun, Oct 25, 2015 at 10:27 AM, Filipe Bezerra de Sousa <
notifications@github.com> wrote:

> You need the check if your laptop supports hardware acceleration, because
> HAXM is a component included in the SDK Manager, also included in the
> Android Studio installation.
>
> If you detect that your laptop don't support hardware acceleration, try
> uninstalling HAXM:
>
> [image: haxm]
> <https://cloud.githubusercontent.com/assets/1006095/10714112/b187949e-7ac3-11e5-9e9a-fe6dd86469ab.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aporter/coursera-android/issues/42#issuecomment-150891866>
> .
>



-- 
Alok

**Comment by filipebezerra** [comment]
Hi, you can check [here](https://software.intel.com/en-us/android/articles/intel-hardware-accelerated-execution-manager).

Or if you have troubles check [here](http://stackoverflow.com/questions/27668832/haxm-hardware-requirements).

And I recommend you always read the docummentation, [see here](http://developer.android.com/intl/pt-br/tools/devices/emulator.html#accel-vm)
