### ISSUE TITLE
Migrating projects to android studio. 

### ISSUE THREAD

**Issue by SauravDas90** [aporter/coursera-android#47]
Hi, I am being unable to build the projects in Android studio. Can anyone give me any blog or tutorial link to set these projects in Android studio. 

Also what steps should I follow to migrate it from Eclipse to Android studio.

Thanks in advance.

Saurav

**Comment by lost-vetern** [comment]
http://www.ytpak.com/watch?v=jliH9hAQMOI

**Comment by SauravDas90** [comment]
thanks @lost-vetern it was a good one for starting from scratch, but I am specifically looking for importing projects in android studio

**Comment by Adverte** [comment]
SauravDas90 you can use for this task Android studio menu "import from Eclipse"

**Comment by snufflesrea** [comment]
same request. Anybody can advise good reference on how to import the project.
I tried to import the project to my android studio but keep failing

**Comment by atiartalukdar** [comment]
Its very simple , You can check this video: https://www.youtube.com/watch?v=6SixOwb_2hE
