### ISSUE TITLE
naming convention for STATE constants on Week 2 - TheActivityClass.java

### ISSUE THREAD

**Issue by fedmich** [aporter/coursera-android#5]
Hi guys,
Based on http://developer.android.com/training/basics/activity-lifecycle/recreating.html
Shouldn't we be using STATE_\* for the naming conventions of our states?

It's a small issue but I think the codes you put there

```
private static final String RESTART_KEY = "restart";
private static final String RESUME_KEY = "resume";
private static final String START_KEY = "start";
private static final String CREATE_KEY = "create";
```

ought to be

```
private static final String STATE_RESTART_KEY = "restart";
private static final String STATE_RESUME_KEY = "resume";
private static final String STATE_START_KEY = "start";
private static final String STATE_CREATE_KEY = "create";
```

**Comment by deadlydragon00** [comment]
Hi @fedmich no need to change that code above since all of them do have the "KEY" at the end , basically if you do STATE_!_KEY , "KEY" becomes redundant/pointless since STATE is already defining the group , or else you can do STATE_RESTART then git rid of the word "KEY" , alternatives use ENUM.
